#!/usr/bin/env python3
"""Generate FAQPage JSON-LD from faq.html's <details class="pg-faq"> blocks.

Idempotent: replaces the block between the markers if present, else
injects it before </head>. Keeps the structured data in sync with the
visible Q&As so rich results never drift from the page copy.

Usage: python3 tools/generate_faq_jsonld.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
FAQ = ROOT / 'faq.html'
MARK_START = '<!-- FAQPage JSON-LD (generated by tools/generate_faq_jsonld.py) -->'
MARK_END = '<!-- /FAQPage JSON-LD -->'

BLOCK_RE = re.compile(
    r'<details class="pg-faq"><summary>(.*?)</summary><p>(.*?)</p></details>',
    re.S)


def main() -> None:
    text = FAQ.read_text(encoding='utf-8')
    pairs = [(q.strip(), a.strip()) for q, a in BLOCK_RE.findall(text)]
    if not pairs:
        raise SystemExit(f'no <details class="pg-faq"> blocks found in {FAQ}')

    schema = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
            {
                '@type': 'Question',
                'name': q,
                'acceptedAnswer': {'@type': 'Answer', 'text': a},
            }
            for q, a in pairs
        ],
    }
    js = json.dumps(schema, ensure_ascii=False, indent=2)
    block = (
        f'{MARK_START}\n'
        '<script type="application/ld+json">\n'
        f'{js}\n'
        '</script>\n'
        f'{MARK_END}'
    )

    if MARK_START in text:
        start = text.index(MARK_START)
        end = text.index(MARK_END) + len(MARK_END)
        text = text[:start] + block + text[end:]
        print(f'replaced FAQPage JSON-LD ({len(pairs)} questions)')
    else:
        if '</head>' not in text:
            raise SystemExit(f'no </head> in {FAQ}')
        text = text.replace('</head>', f'{block}\n</head>', 1)
        print(f'injected FAQPage JSON-LD ({len(pairs)} questions)')
    FAQ.write_text(text, encoding='utf-8')


if __name__ == '__main__':
    main()
